import {NextResponse} from 'next/server';
import {GET as dashboardGET} from '../dashboard/route';

export const dynamic='force-dynamic';
export const maxDuration=60;

type CaptureFund={estimateNav:number|null;estimateChange:number|null;marketMove:number|null;relativeCorrection:number|null;sectorScore:number;relativeScore:number;confirmationScore:number;qualityScore:number;score:number;signal:string;mappedLive:number;mappedTotal:number};

function istNow(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',weekday:'short',hour12:false}).formatToParts(new Date());const get=(type:string)=>parts.find(part=>part.type===type)?.value??'';return{weekday:get('weekday'),year:get('year'),month:get('month'),day:get('day'),hour:Number(get('hour')),minute:Number(get('minute'))};}
function captureWindow(p:ReturnType<typeof istNow>){return p.weekday!=='Sat'&&p.weekday!=='Sun'&&p.hour===14&&p.minute>=25&&p.minute<=40;}

export async function GET(){const p=istNow();const date=`${p.year}-${p.month}-${p.day}`;if(!captureWindow(p))return NextResponse.json({ok:true,captured:false,ready:false,date,reason:'2:30 PM capture runs only 14:25–14:40 IST. The client stores a successful same-day snapshot locally.'},{headers:{'Cache-Control':'no-store'}});try{const response=await dashboardGET();if(!response.ok)throw new Error('dashboard unavailable');const data=await response.json() as {summary?:Record<string,number>;funds?:Array<{code:string;nav:number|null;previousNav:number|null;change:number|null;sectorMove:number|null;beta:number|null;relativeCorrection:number|null;sectorScore:number;relativeScore:number;confirmationScore:number;qualityScore:number;score:number;signal:string;mappedLive:number;mappedTotal:number}>};const funds:Record<string,CaptureFund>={};for(const fund of data.funds??[]){const base=fund.previousNav??(fund.nav!=null&&fund.change!=null?fund.nav/(1+fund.change/100):null);const move=fund.sectorMove==null?null:fund.sectorMove*(fund.beta??1);funds[fund.code]={estimateNav:base!=null&&move!=null?base*(1+move/100):null,estimateChange:move,marketMove:move,relativeCorrection:fund.relativeCorrection,sectorScore:fund.sectorScore,relativeScore:fund.relativeScore,confirmationScore:fund.confirmationScore,qualityScore:fund.qualityScore,score:fund.score,signal:fund.signal,mappedLive:fund.mappedLive,mappedTotal:fund.mappedTotal};}const snapshot={date,capturedAt:new Date().toISOString(),timezone:'Asia/Kolkata',funds,summary:data.summary??{}};return NextResponse.json({ok:true,captured:true,ready:true,snapshot},{headers:{'Cache-Control':'public, s-maxage=21600, stale-while-revalidate=600','CDN-Cache-Control':'public, s-maxage=21600, stale-while-revalidate=600'}});}catch(error){console.error('2:30 PM capture failed',error);return NextResponse.json({ok:false,captured:false,ready:false,date,error:'2:30 PM capture failed'},{status:500,headers:{'Cache-Control':'no-store'}});}}
