'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,ArrowDownRight,ArrowUpRight,BarChart3,Clock3,RefreshCw,Sparkles,Target,TrendingDown,ShieldCheck,Search,TimerReset,BrainCircuit,WalletCards,ShieldAlert,FlaskConical} from 'lucide-react';

type Fund={code:string;name:string;category:string;nav:number|null;previousNav:number|null;change:number|null;date:string|null;status:string;sectorMove:number|null;leadSector:string;leadMove:number|null;relativeCorrection:number|null;score:number;signal:string;reason:string};
type Index={name:string;value:number|null;change:number|null;status:string;group:'BROAD'|'SECTORAL'|'THEMATIC'};
type Sector={name:string;value:number|null;change:number|null;status:string;severity:string};
type Summary={trackedFunds:number;liveFunds:number;liveIndices:number;fallingIndices:number;buySignals:number;accumulateSignals:number};
type ThreePmFund={estimateNav:number|null;estimateChange:number|null;marketMove:number|null};
type ThreePmSnapshot={date:string;capturedAt:string;funds:Record<string,ThreePmFund>};
type Backtest={code:string;name:string;sampleCount:number;threshold:number;horizon:number;winRate:number|null;averageForward:number|null;medianForward:number|null;bestForward:number|null;worstForward:number|null};

const money=(n:number|null)=>n==null?'—':`₹${n.toFixed(4)}`;
const pct=(n:number|null)=>n==null?'—':`${n>=0?'+':''}${n.toFixed(2)}%`;
const cls=(n:number|null)=>n==null?'muted':n<0?'negative':'positive';
function istParts(){const now=new Date();const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',weekday:'short',hour12:false}).formatToParts(now);const get=(t:string)=>parts.find(p=>p.type===t)?.value||'';return{now,year:get('year'),month:get('month'),day:get('day'),hour:Number(get('hour')),minute:Number(get('minute')),second:Number(get('second')),weekday:get('weekday')}}
function isTradingDay(p:ReturnType<typeof istParts>){return p.weekday!=='Sat'&&p.weekday!=='Sun'}
function inThreePmWindow(p:ReturnType<typeof istParts>){return isTradingDay(p)&&((p.hour===14&&p.minute>=55)||(p.hour===15&&p.minute<=5))}
function snapshotKey(p:ReturnType<typeof istParts>){return`${p.year}-${p.month}-${p.day}`}
function estimateThreePm(f:Fund,snapshot:ThreePmSnapshot|null,liveWindow:boolean){const s=snapshot?.funds?.[f.code];const move=s?.marketMove??(liveWindow?f.sectorMove:null);const base=f.previousNav??(f.nav!=null&&f.change!=null?f.nav/(1+f.change/100):null);if(base==null||move==null)return{nav:null,change:null,move};return{nav:base*(1+move/100),change:move,move}}

export default function Home(){
 const [funds,setFunds]=useState<Fund[]>([]),[indices,setIndices]=useState<Index[]>([]),[sectors,setSectors]=useState<Sector[]>([]),[summary,setSummary]=useState<Summary|null>(null),[updated,setUpdated]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[indexFilter,setIndexFilter]=useState<'ALL'|'BROAD'|'SECTORAL'|'THEMATIC'>('ALL'),[indexSearch,setIndexSearch]=useState('');
 const [threePmSnapshot,setThreePmSnapshot]=useState<ThreePmSnapshot|null>(null),[investAmount,setInvestAmount]=useState(10000),[backtests,setBacktests]=useState<Backtest[]>([]),[backtesting,setBacktesting]=useState(false),[btThreshold,setBtThreshold]=useState(1),[btHorizon,setBtHorizon]=useState(20);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/dashboard',{cache:'no-store'});if(!r.ok)throw new Error('API');const j=await r.json();const nextFunds:Fund[]=j.funds||[];setFunds(nextFunds);setIndices(j.indices||[]);setSectors(j.sectors||[]);setSummary(j.summary||null);setUpdated(j.updatedAt||'');const p=istParts(),key=snapshotKey(p);if(typeof window!=='undefined'){const stored=window.localStorage.getItem('ak-mf-3pm-snapshot');if(stored){try{const parsed=JSON.parse(stored) as ThreePmSnapshot;if(parsed.date===key)setThreePmSnapshot(parsed);}catch{}}if(inThreePmWindow(p)){const snap:ThreePmSnapshot={date:key,capturedAt:new Date().toISOString(),funds:{}};for(const f of nextFunds){const est=estimateThreePm(f,null,true);snap.funds[f.code]={estimateNav:est.nav,estimateChange:est.change,marketMove:est.move}}window.localStorage.setItem('ak-mf-3pm-snapshot',JSON.stringify(snap));setThreePmSnapshot(snap)}}}catch{setError('Live market feed unavailable. Press Refresh Now to retry.')}finally{setLoading(false)}},[]);
 useEffect(()=>{let timer:number;const tick=async()=>{await load();const p=istParts();timer=window.setTimeout(tick,inThreePmWindow(p)?30_000:15*60*1000)};tick();return()=>window.clearTimeout(timer)},[load]);
 const top=useMemo(()=>funds.slice(0,5),[funds]);const best=useMemo(()=>funds.filter(x=>x.signal==='BUY'||x.signal==='ACCUMULATE').slice(0,3),[funds]);const visibleIndices=useMemo(()=>indices.filter(x=>(indexFilter==='ALL'||x.group===indexFilter)&&x.name.toLowerCase().includes(indexSearch.toLowerCase())),[indices,indexFilter,indexSearch]);const groups=[['BROAD','Broad Market'],['SECTORAL','Sectoral'],['THEMATIC','Thematic']] as const;const p=istParts();const threePmLive=inThreePmWindow(p);const threePmDate=threePmSnapshot?.date||'—';
 const nifty=indices.find(x=>x.name==='NIFTY 50');const broad=indices.filter(x=>x.group==='BROAD'&&x.change!=null);const broadFall=broad.length?broad.filter(x=>(x.change??0)<0).length/broad.length:0;const sectorLive=sectors.filter(x=>x.change!=null);const sectorFall=sectorLive.length?sectorLive.filter(x=>(x.change??0)<0).length/sectorLive.length:0;const avgSector=sectorLive.length?sectorLive.reduce((a,x)=>a+(x.change??0),0)/sectorLive.length:0;
 const regime=nifty?.change!=null&&nifty.change<=-2?'PANIC / AGGRESSIVE ACCUMULATION':nifty?.change!=null&&nifty.change<=-1?'STRONG CORRECTION':nifty?.change!=null&&nifty.change<0&&broadFall>=.55?'SELECTIVE ACCUMULATION':nifty?.change!=null&&nifty.change>=.8&&broadFall<.4?'RISK-ON / NORMAL SIP':'NEUTRAL';
 const regimeClass=regime.includes('PANIC')||regime.includes('STRONG')?'hot':regime.includes('SELECTIVE')?'warm':'cool';
 const deployMultiplier=regime.includes('PANIC')?2:regime.includes('STRONG')?1.5:regime.includes('SELECTIVE')?1.2:1;
 const allocation=useMemo(()=>{const eligible=funds.filter(f=>f.score>=45&&f.signal!=='WAIT').slice(0,6);if(!eligible.length)return[];const weights=eligible.map(f=>Math.max(1,f.score-40));const total=weights.reduce((a,b)=>a+b,0);const deploy=Math.min(investAmount,Math.round(investAmount*deployMultiplier));return eligible.map((f,i)=>({fund:f,amount:Math.round(deploy*weights[i]/total/100)*100})).filter(x=>x.amount>0)},[funds,investAmount,deployMultiplier]);
 const quality=(f:Fund)=>Math.round(Math.max(35,Math.min(92,50+f.score*.35+(f.category.includes('Large')||f.category==='Diversified'?12:0)-(f.category==='Small Cap'?8:0))));
 const overlap=useMemo(()=>{const cats=new Map<string,number>();for(const f of allocation){cats.set(f.fund.category,(cats.get(f.fund.category)||0)+f.amount)}return [...cats.entries()].sort((a,b)=>b[1]-a[1])},[allocation]);
 const runBacktest=async()=>{setBacktesting(true);try{const r=await fetch(`/api/backtest?threshold=${btThreshold}&horizon=${btHorizon}`,{cache:'no-store'});const j=await r.json();setBacktests(j.results||[])}catch{setError('Backtest could not be loaded. Try again.')}finally{setBacktesting(false)}};
 return <main>
  <header className="hero"><div><div className="eyebrow"><span className="live-dot"/> AKASH • PREMIUM INVESTMENT TERMINAL</div><h1>AKASH MUTUAL FUNDS</h1><p>19-fund opportunity intelligence • market regime • 3 PM NAV engine • dynamic allocation</p></div><div className="hero-actions"><div className="last-sync"><Clock3 size={14}/>{updated?new Date(updated).toLocaleString('en-IN'):'Syncing market…'}</div><button onClick={load} disabled={loading} className="refresh"><RefreshCw size={17} className={loading?'spin':''}/>{loading?'Syncing…':'Refresh Now'}</button></div></header>
  <div className="ticker">{indices.slice(0,8).map(x=><div key={x.name} className="ticker-item"><span>{x.name.replace('NIFTY ','')}</span><b className={cls(x.change)}>{pct(x.change)}</b></div>)}</div>
  {error&&<div className="error">{error}</div>}
  <section className="cutoff-panel"><div className="cutoff-main"><div className="cutoff-icon"><TimerReset size={20}/></div><div><span className="section-kicker">3 PM NAV CUT-OFF ENGINE</span><h2>3 PM Purchase Snapshot</h2><p>Estimates the same-day closing NAV from the mapped index snapshot. It is an estimate, not an official intraday NAV.</p></div></div><div className="cutoff-status"><b className={threePmLive?'positive':''}>{threePmLive?'3 PM WINDOW LIVE':'3 PM SNAPSHOT'}</b><span>{threePmLive?'Capturing every 30 seconds':'Last captured: '+threePmDate}</span></div></section>
  <section className="stats"><div className="stat"><span>Tracked Funds</span><b>{summary?.trackedFunds??19}</b><small>{summary?.liveFunds??0} NAV feeds live</small></div><div className="stat"><span>BUY Signals</span><b className="positive">{summary?.buySignals??0}</b><small>{summary?.accumulateSignals??0} accumulate setups</small></div><div className="stat"><span>Falling Indices</span><b className="negative">{summary?.fallingIndices??0}</b><small>Across monitored NIFTY universe</small></div><div className="stat"><span>Index Engine</span><b className="positive">{loading?'SYNCING':'LIVE'}</b><small>{summary?.liveIndices??0}/{indices.length||0} indices live</small></div></section>
  <section className="advanced-grid"><div className={`regime-card ${regimeClass}`}><div className="card-icon"><BrainCircuit size={20}/></div><div><span className="section-kicker">MARKET REGIME ENGINE</span><h2>{regime}</h2><p>NIFTY 50 {pct(nifty?.change??null)} • Broad-market breadth {Math.round(broadFall*100)}% falling • Sector breadth {Math.round(sectorFall*100)}% falling.</p></div><strong className="regime-mult">{deployMultiplier.toFixed(1)}×</strong></div><div className="allocation-card"><div className="panelhead"><div><span className="section-kicker">SMART DEPLOYMENT</span><h2>Today's Investment Plan</h2></div><WalletCards size={19}/></div><div className="amount-row"><label>Capital<input type="number" min="1000" step="500" value={investAmount} onChange={e=>setInvestAmount(Number(e.target.value)||0)}/></label><div><span>Suggested deploy</span><b>₹{Math.round(investAmount*deployMultiplier).toLocaleString('en-IN')}</b></div></div><div className="allocation-list">{allocation.length?allocation.map(x=><div className="allocation-row" key={x.fund.code}><div><strong>{x.fund.name}</strong><small>{x.fund.signal} • score {x.fund.score}</small></div><b>₹{x.amount.toLocaleString('en-IN')}</b></div>):<div className="empty compact"><ShieldCheck size={20}/><strong>Hold / wait</strong><span>No qualifying deployment setup.</span></div>}</div></div></section>
  <section className="insight-strip"><div><span className="section-kicker">RISK CONTROL</span><strong>Don't chase the biggest fall</strong><small>Require fund correction + mapped-sector confirmation + relative discount before aggressive action.</small></div><div><span className="section-kicker">QUALITY PROXY</span><strong>{funds[0]?`${funds[0].name}: ${quality(funds[0])}/100`: 'Loading…'}</strong><small>Category/score proxy only; official Riskometer remains the regulatory risk reference.</small></div><div><span className="section-kicker">CONCENTRATION</span><strong>{overlap.length?`${overlap[0][0]} ${Math.round(overlap[0][1]/Math.max(1,investAmount*deployMultiplier)*100)}%`: '—'}</strong><small>Model allocation overlap proxy; not portfolio holdings overlap.</small></div></section>
  <section className="panel index-monitor"><div className="panelhead"><div><span className="section-kicker">NIFTY INDEX MONITOR</span><h2>Complete Market Map</h2></div><BarChart3 size={19}/></div><div className="index-tools"><div className="index-tabs"><button className={indexFilter==='ALL'?'active':''} onClick={()=>setIndexFilter('ALL')}>ALL <em>{indices.length}</em></button>{groups.map(([key,label])=><button key={key} className={indexFilter===key?'active':''} onClick={()=>setIndexFilter(key)}>{label} <em>{indices.filter(x=>x.group===key).length}</em></button>)}</div><label className="searchbox"><Search size={15}/><input value={indexSearch} onChange={e=>setIndexSearch(e.target.value)} placeholder="Search Nifty index…"/></label></div><div className="index-grid">{visibleIndices.map(x=><div className={`index-card ${x.change!=null&&x.change<0?'down':''}`} key={x.name}><div className="index-card-top"><span>{x.group}</span><b className={cls(x.change)}>{pct(x.change)}</b></div><strong>{x.name}</strong><small>{x.value!=null?x.value.toLocaleString('en-IN',{maximumFractionDigits:2}):'Feed unavailable'}</small></div>)}</div></section>
  <section className="main-grid"><div className="panel market-panel"><div className="panelhead"><div><span className="section-kicker">MARKET INTELLIGENCE</span><h2>Market Pulse</h2></div><Activity size={19}/></div><div className="market-list">{indices.filter(x=>x.change!=null).sort((a,b)=>(a.change??0)-(b.change??0)).slice(0,10).map(x=><div className="market-row" key={x.name}><div><strong>{x.name}</strong><small>{x.value!=null?x.value.toLocaleString('en-IN',{maximumFractionDigits:2}):'Feed unavailable'}</small></div><div className={`move ${cls(x.change)}`}>{x.change!=null&&x.change<0?<ArrowDownRight size={15}/>:<ArrowUpRight size={15}/>} {pct(x.change)}</div></div>)}</div></div><div className="panel opportunity-panel"><div className="panelhead"><div><span className="section-kicker">MODEL OUTPUT</span><h2>Top Opportunities</h2></div><Sparkles size={19}/></div>{top.map((f,i)=><div className="op" key={f.code}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="opmain"><strong>{f.name}</strong><small>{f.category} • Trigger: {f.reason}</small><div className="mini-track"><i style={{width:`${f.score}%`}}/></div></div><div className="score"><b>{f.score}</b><span className={`badge ${f.signal.toLowerCase()}`}>{f.signal}</span></div></div>)}</div></section>
  <section className="analysis-grid"><div className="panel"><div className="panelhead"><div><span className="section-kicker">SECTOR HEATMAP</span><h2>Where the market is weak</h2></div><TrendingDown size={19}/></div><div className="heatmap">{sectors.map(s=><div key={s.name} className={`heat ${s.change!=null&&s.change<0?'down':'up'}`}><span>{s.name.replace('NIFTY ','')}</span><b>{pct(s.change)}</b></div>)}</div></div><div className="panel decision"><div className="panelhead"><div><span className="section-kicker">DECISION DESK</span><h2>Today's Action Plan</h2></div><Target size={19}/></div>{best.length?best.map(f=><div className="decision-row" key={f.code}><div><strong>{f.name}</strong><small>{f.signal} • score {f.score} • {f.reason}{f.change!=null?` • NAV ${pct(f.change)}`:''}</small></div><span className={`badge ${f.signal.toLowerCase()}`}>{f.signal}</span></div>):<div className="empty"><ShieldCheck size={22}/><strong>No BUY / ACCUMULATE setup</strong><span>Wait for a stronger correction plus sector confirmation.</span></div>}<div className="rule">A signal is a decision-support estimate, not a guaranteed return. It should not override the scheme's objective, Riskometer or your own suitability.</div></div></section>
  <section className="panel tablepanel"><div className="panelhead"><div><span className="section-kicker">PORTFOLIO UNIVERSE</span><h2>All 19 Funds</h2></div><small>Ranked by opportunity score</small></div><div className="tablewrap"><table><thead><tr><th>Fund</th><th>Theme</th><th>NAV</th><th>3 PM NAV EST.</th><th>3 PM Δ</th><th>Sector Signal</th><th>Quality</th><th>Score</th><th>Action</th></tr></thead><tbody>{funds.map(f=>{const est=estimateThreePm(f,threePmSnapshot,threePmLive);return <tr key={f.code}><td><strong>{f.name}</strong><small>{f.code} • NAV date {f.date||'—'}</small></td><td>{f.category}</td><td>{money(f.nav)}</td><td><strong className={cls(est.change)}>{money(est.nav)}</strong><small>{est.move!=null?`Mapped move ${pct(est.move)}`:'3 PM snapshot not captured'}</small></td><td className={cls(est.change)}>{pct(est.change)}</td><td><span className={f.leadMove!=null&&f.leadMove<0?'sector-risk':'sector-ok'}>{f.leadSector.replace('NIFTY ','')} {pct(f.leadMove)}</span><small>{f.relativeCorrection!=null?`Relative ${pct(f.relativeCorrection)}`:'No relative feed'}</small></td><td><div className="quality-pill">{quality(f)}/100</div></td><td><div className="score-cell"><div className="bar"><i style={{width:`${f.score}%`}}/></div><b>{f.score}</b></div></td><td><span className={`badge ${f.signal.toLowerCase()}`}>{f.signal}</span></td></tr>})}</tbody></table></div></section>
  <section className="panel backtest-panel"><div className="panelhead"><div><span className="section-kicker">STRATEGY LAB</span><h2>Buy-the-Dip Backtest</h2></div><FlaskConical size={19}/></div><div className="backtest-controls"><label>Daily fall trigger <select value={btThreshold} onChange={e=>setBtThreshold(Number(e.target.value))}><option value="0.5">-0.5%</option><option value="1">-1.0%</option><option value="1.5">-1.5%</option><option value="2">-2.0%</option></select></label><label>Forward horizon <select value={btHorizon} onChange={e=>setBtHorizon(Number(e.target.value))}><option value="10">10 sessions</option><option value="20">20 sessions</option><option value="40">40 sessions</option><option value="60">60 sessions</option></select></label><button className="refresh secondary" onClick={runBacktest} disabled={backtesting}>{backtesting?'Testing…':'Run Backtest'}</button></div>{backtests.length?<div className="backtest-grid">{backtests.slice(0,8).map(x=><div className="bt-card" key={x.code}><strong>{x.name}</strong><small>{x.sampleCount} historical signals</small><div><b>{x.winRate==null?'—':x.winRate.toFixed(0)+'%'}</b><span>win rate</span></div><div><b className={cls(x.averageForward)}>{pct(x.averageForward)}</b><span>avg forward</span></div><div className="bt-range"><span>Best {pct(x.bestForward)}</span><span>Worst {pct(x.worstForward)}</span></div></div>)}</div>:<div className="empty compact"><FlaskConical size={20}/><strong>Test the strategy before trusting it</strong><span>This lab measures historical NAV response after daily fund drawdowns; it is not a promise of future performance.</span></div>}</section>
  <section className="panel safety-panel"><div><ShieldAlert size={20}/><div><span className="section-kicker">RISK & EXECUTION GUARDRAILS</span><h2>Use the engine as a decision aid</h2><p>3 PM timing is useful only when the transaction and money meet the applicable cut-off conditions. The official NAV is a closing NAV, not a live intraday NAV. Riskometer and scheme suitability remain mandatory checks.</p></div></div><div className="guardrails"><span>✓ No blind buying on one-day falls</span><span>✓ Prefer multiple-index confirmation</span><span>✓ Cap single-fund deployment</span><span>✓ Backtest before changing weights</span></div></section>
  <footer><b>AKASH MUTUAL FUNDS</b> • AMFI NAVAll + MFAPI history + NSE All Indices with Yahoo fallback • 3 PM estimate is model-derived; official NAV remains end-of-day.</footer>
 </main>
}
