'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,ArrowDownRight,ArrowUpRight,BarChart3,Clock3,RefreshCw,Sparkles,Target,TrendingDown,ShieldCheck,Search} from 'lucide-react';

type Fund={code:string;name:string;category:string;nav:number|null;previousNav:number|null;change:number|null;date:string|null;status:string;sectorMove:number;leadSector:string;score:number;signal:string};
type Index={name:string;value:number|null;change:number|null;status:string;group:'BROAD'|'SECTORAL'|'THEMATIC'};
type Sector={name:string;value:number|null;change:number|null;status:string;severity:string};
type Summary={trackedFunds:number;liveFunds:number;liveIndices:number;fallingIndices:number;buySignals:number;accumulateSignals:number};
const money=(n:number|null)=>n==null?'—':`₹${n.toFixed(4)}`;const pct=(n:number|null)=>n==null?'—':`${n>=0?'+':''}${n.toFixed(2)}%`;const cls=(n:number|null)=>n==null?'muted':n<0?'negative':'positive';
export default function Home(){
 const [funds,setFunds]=useState<Fund[]>([]),[indices,setIndices]=useState<Index[]>([]),[sectors,setSectors]=useState<Sector[]>([]),[summary,setSummary]=useState<Summary|null>(null),[updated,setUpdated]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[indexFilter,setIndexFilter]=useState<'ALL'|'BROAD'|'SECTORAL'|'THEMATIC'>('ALL'),[indexSearch,setIndexSearch]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/dashboard',{cache:'no-store'});if(!r.ok)throw new Error('API');const j=await r.json();setFunds(j.funds||[]);setIndices(j.indices||[]);setSectors(j.sectors||[]);setSummary(j.summary||null);setUpdated(j.updatedAt||'')}catch{setError('Live market feed unavailable. Press Refresh Now to retry.')}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const t=setInterval(load,15*60*1000);return()=>clearInterval(t)},[load]);
 const top=useMemo(()=>funds.slice(0,5),[funds]);const best=useMemo(()=>funds.filter(x=>x.signal==='BUY'||x.signal==='ACCUMULATE').slice(0,3),[funds]);
 const visibleIndices=useMemo(()=>indices.filter(x=>(indexFilter==='ALL'||x.group===indexFilter)&&x.name.toLowerCase().includes(indexSearch.toLowerCase())),[indices,indexFilter,indexSearch]);
 const groups=[['BROAD','Broad Market'],['SECTORAL','Sectoral'],['THEMATIC','Thematic']] as const;
 return <main>
  <header className="hero"><div><div className="eyebrow"><span className="live-dot"/> AKASH • PREMIUM INVESTMENT TERMINAL</div><h1>AKASH MUTUAL FUNDS</h1><p>19-fund opportunity intelligence • comprehensive NIFTY market map • live market pulse</p></div><div className="hero-actions"><div className="last-sync"><Clock3 size={14}/>{updated?new Date(updated).toLocaleString('en-IN'):'Syncing market…'}</div><button onClick={load} disabled={loading} className="refresh"><RefreshCw size={17} className={loading?'spin':''}/>{loading?'Syncing…':'Refresh Now'}</button></div></header>
  <div className="ticker">{indices.slice(0,8).map(x=><div key={x.name} className="ticker-item"><span>{x.name.replace('NIFTY ','')}</span><b className={cls(x.change)}>{pct(x.change)}</b></div>)}</div>
  {error&&<div className="error">{error}</div>}
  <section className="stats"><div className="stat"><span>Tracked Funds</span><b>{summary?.trackedFunds??19}</b><small>{summary?.liveFunds??0} NAV feeds live</small></div><div className="stat"><span>BUY Signals</span><b className="positive">{summary?.buySignals??0}</b><small>{summary?.accumulateSignals??0} accumulate setups</small></div><div className="stat"><span>Falling Indices</span><b className="negative">{summary?.fallingIndices??0}</b><small>Across monitored NIFTY universe</small></div><div className="stat"><span>Index Engine</span><b className="positive">{loading?'SYNCING':'LIVE'}</b><small>{summary?.liveIndices??0}/{indices.length||0} indices available</small></div></section>

  <section className="panel index-monitor"><div className="panelhead"><div><span className="section-kicker">NIFTY INDEX MONITOR</span><h2>Complete Market Map</h2></div><BarChart3 size={19}/></div><div className="index-tools"><div className="index-tabs"><button className={indexFilter==='ALL'?'active':''} onClick={()=>setIndexFilter('ALL')}>ALL <em>{indices.length}</em></button>{groups.map(([key,label])=><button key={key} className={indexFilter===key?'active':''} onClick={()=>setIndexFilter(key)}>{label} <em>{indices.filter(x=>x.group===key).length}</em></button>)}</div><label className="searchbox"><Search size={15}/><input value={indexSearch} onChange={e=>setIndexSearch(e.target.value)} placeholder="Search Nifty index…"/></label></div><div className="index-grid">{visibleIndices.map(x=><div className={`index-card ${x.change!=null&&x.change<0?'down':''}`} key={x.name}><div className="index-card-top"><span>{x.group}</span><b className={cls(x.change)}>{pct(x.change)}</b></div><strong>{x.name}</strong><small>{x.value!=null?x.value.toLocaleString('en-IN',{maximumFractionDigits:2}):'Feed unavailable'}</small></div>)}</div></section>

  <section className="main-grid"><div className="panel market-panel"><div className="panelhead"><div><span className="section-kicker">MARKET INTELLIGENCE</span><h2>Market Pulse</h2></div><Activity size={19}/></div><div className="market-list">{indices.filter(x=>x.change!=null).sort((a,b)=>(a.change??0)-(b.change??0)).slice(0,10).map(x=><div className="market-row" key={x.name}><div><strong>{x.name}</strong><small>{x.value!=null?x.value.toLocaleString('en-IN',{maximumFractionDigits:2}):'Feed unavailable'}</small></div><div className={`move ${cls(x.change)}`}>{x.change!=null&&x.change<0?<ArrowDownRight size={15}/>:<ArrowUpRight size={15}/>} {pct(x.change)}</div></div>)}</div></div><div className="panel opportunity-panel"><div className="panelhead"><div><span className="section-kicker">MODEL OUTPUT</span><h2>Top Opportunities</h2></div><Sparkles size={19}/></div>{top.map((f,i)=><div className="op" key={f.code}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="opmain"><strong>{f.name}</strong><small>{f.category} • Trigger: {f.leadSector}</small><div className="mini-track"><i style={{width:`${f.score}%`}}/></div></div><div className="score"><b>{f.score}</b><span className={`badge ${f.signal.toLowerCase()}`}>{f.signal}</span></div></div>)}</div></section>

  <section className="analysis-grid"><div className="panel"><div className="panelhead"><div><span className="section-kicker">SECTOR HEATMAP</span><h2>Where the market is weak</h2></div><TrendingDown size={19}/></div><div className="heatmap">{sectors.map(s=><div key={s.name} className={`heat ${s.change!=null&&s.change<0?'down':'up'}`}><span>{s.name.replace('NIFTY ','')}</span><b>{pct(s.change)}</b></div>)}</div></div><div className="panel decision"><div className="panelhead"><div><span className="section-kicker">DECISION DESK</span><h2>Today's Action Plan</h2></div><Target size={19}/></div>{best.length?best.map(f=><div className="decision-row" key={f.code}><div><strong>{f.name}</strong><small>{f.category} • score {f.score} • {f.leadSector}</small></div><span className={`badge ${f.signal.toLowerCase()}`}>{f.signal}</span></div>):<div className="empty"><ShieldCheck size={22}/><strong>No aggressive BUY setup</strong><span>Wait for a stronger correction/reversal signal.</span></div>}<div className="rule">Signals combine index weakness, fund NAV correction and category quality. They are analytical estimates, not guaranteed returns.</div></div></section>

  <section className="panel tablepanel"><div className="panelhead"><div><span className="section-kicker">PORTFOLIO UNIVERSE</span><h2>All 19 Funds</h2></div><small>Ranked by opportunity score</small></div><div className="tablewrap"><table><thead><tr><th>Fund</th><th>Theme</th><th>NAV</th><th>NAV Δ</th><th>Sector Signal</th><th>Score</th><th>Action</th></tr></thead><tbody>{funds.map(f=><tr key={f.code}><td><strong>{f.name}</strong><small>{f.code} • NAV date {f.date||'—'}</small></td><td>{f.category}</td><td>{money(f.nav)}</td><td className={cls(f.change)}>{pct(f.change)}</td><td><span className={f.sectorMove<0?'sector-risk':'sector-ok'}>{f.leadSector} {pct(f.sectorMove)}</span></td><td><div className="score-cell"><div className="bar"><i style={{width:`${f.score}%`}}/></div><b>{f.score}</b></div></td><td><span className={`badge ${f.signal.toLowerCase()}`}>{f.signal}</span></td></tr>)}</tbody></table></div></section>
  <footer><b>AKASH MUTUAL FUNDS</b> • Data: MFAPI + NSE All Indices with Yahoo fallback • NSE Indices maintains broad-market, sectoral and thematic index families. NAV is end-of-day; market movement is used for opportunity analysis.</footer>
 </main>
}
