type Point={date:string;value:number};
type Group='BROAD'|'SECTORAL'|'THEMATIC';
export type IndexRow={name:string;value:number|null;change:number|null;group:Group;status:'LIVE'|'UNAVAILABLE';source:'NSE'|'YAHOO'|'UNAVAILABLE'};
export type FundCfg={code:string;name:string;category:string;proxies:string[]};

export const FUNDS:FundCfg[]=[
 {code:'120843',name:'Quant Flexi Cap Fund Direct Growth',category:'Diversified',proxies:['NIFTY 50','NIFTY SERVICES SECTOR']},
 {code:'120826',name:'Quant Large and Mid Cap Fund Direct Growth',category:'Large & Mid Cap',proxies:['NIFTY 50','NIFTY MIDCAP 150','NIFTY NEXT 50']},
 {code:'120821',name:'Quant Multi Asset Fund Direct Growth',category:'Multi Asset',proxies:['NIFTY 50','NIFTY BANK','NIFTY 500']},
 {code:'120823',name:'Quant Multi Cap Fund Direct Growth',category:'Multi Cap',proxies:['NIFTY 50','NIFTY NEXT 50','NIFTY MIDCAP 150']},
 {code:'120833',name:'Quant Infrastructure Fund Direct Growth',category:'Infrastructure',proxies:['NIFTY INFRASTRUCTURE','NIFTY CAPITAL GOODS','NIFTY CEMENT','NIFTY POWER','NIFTY CONSTRUCTION']},
 {code:'151791',name:'Quant BFSI Fund Direct Growth',category:'Banking & Financial',proxies:['NIFTY FINANCIAL SERVICES','NIFTY BANK','NIFTY PRIVATE BANK','NIFTY PSU BANK','NIFTY NBFC','NIFTY INSURANCE']},
 {code:'119827',name:'SBI Nifty 50 Index Fund Direct Growth',category:'Nifty 50',proxies:['NIFTY 50']},
 {code:'119783',name:'SBI Healthcare Opportunities Fund Direct Growth',category:'Healthcare',proxies:['NIFTY PHARMA','NIFTY HEALTHCARE','NIFTY500 HEALTHCARE']},
 {code:'119727',name:'SBI Focused Equity Fund Direct Growth',category:'Focused Equity',proxies:['NIFTY 50','NIFTY FINANCIAL SERVICES','NIFTY IT']},
 {code:'148490',name:"SBI Children's Benefit Fund Direct Growth",category:'Children',proxies:['NIFTY 50','NIFTY CONSUMER SERVICES']},
 {code:'147946',name:'Bandhan Small Cap Fund Direct Growth',category:'Small Cap',proxies:['NIFTY SMALLCAP 250','NIFTY SMALLCAP 100','NIFTY MIDSMALLCAP 400']},
 {code:'118989',name:'HDFC Mid Cap Opportunities Fund Direct Growth',category:'Mid Cap',proxies:['NIFTY MIDCAP 150','NIFTY MIDCAP 100','NIFTY MIDCAP 50']},
 {code:'143341',name:'UTI Nifty Next 50 Index Fund Direct Growth',category:'Nifty Next 50',proxies:['NIFTY NEXT 50']},
 {code:'150714',name:'UTI Gold ETF FoF Direct Growth',category:'Gold',proxies:['NIFTY COMMODITIES']},
 {code:'125497',name:'SBI Small Cap Fund Direct Growth',category:'Small Cap',proxies:['NIFTY SMALLCAP 250','NIFTY SMALLCAP 100','NIFTY MIDSMALLCAP 400']},
 {code:'120586',name:'ICICI Prudential Value Discovery Fund Direct Growth',category:'Value',proxies:['NIFTY 50','NIFTY FINANCIAL SERVICES','NIFTY PRIVATE BANK','NIFTY REALTY']},
 {code:'120503',name:'Axis ELSS Tax Saver Fund Direct Growth',category:'ELSS',proxies:['NIFTY 50']},
 {code:'144835',name:'Sundaram Services Fund Direct Growth',category:'Services',proxies:['NIFTY SERVICES SECTOR','NIFTY CONSUMER SERVICES','NIFTY COMMERCIAL & TRANSPORT SERVICES']},
 {code:'135800',name:'Tata Digital India Fund Direct Growth',category:'Technology',proxies:['NIFTY IT','NIFTY MIDSMALL IT & TELECOM','NIFTY TELECOMMUNICATIONS']}
];

const INDEXES:[string,Group][]=[
 ...['NIFTY 50','NIFTY NEXT 50','NIFTY 100','NIFTY 200','NIFTY 500','NIFTY MIDCAP 50','NIFTY MIDCAP 100','NIFTY MIDCAP 150','NIFTY SMALLCAP 50','NIFTY SMALLCAP 100','NIFTY SMALLCAP 250','NIFTY MIDSMALLCAP 400'].map(x=>[x,'BROAD']),
 ...['NIFTY BANK','NIFTY FINANCIAL SERVICES','NIFTY IT','NIFTY HEALTHCARE','NIFTY PHARMA','NIFTY AUTO','NIFTY FMCG','NIFTY METAL','NIFTY MEDIA','NIFTY REALTY','NIFTY PRIVATE BANK','NIFTY PSU BANK','NIFTY OIL & GAS','NIFTY CONSUMER DURABLES','NIFTY CAPITAL GOODS','NIFTY POWER','NIFTY TELECOMMUNICATIONS','NIFTY RETAIL','NIFTY INSURANCE','NIFTY NBFC','NIFTY CEMENT','NIFTY CHEMICALS','NIFTY CONSTRUCTION','NIFTY CONSUMER SERVICES','NIFTY COMMERCIAL & TRANSPORT SERVICES','NIFTY HOSPITALS','NIFTY HOUSING FINANCE','NIFTY REITS & REALTY','NIFTY500 HEALTHCARE','NIFTY MIDSMALL FINANCIAL SERVICES','NIFTY MIDSMALL HEALTHCARE','NIFTY MIDSMALL IT & TELECOM'].map(x=>[x,'SECTORAL']),
 ...['NIFTY INFRASTRUCTURE','NIFTY SERVICES SECTOR','NIFTY ENERGY','NIFTY COMMODITIES'].map(x=>[x,'THEMATIC'])
];

const Y:Record<string,string>={
 'NIFTY 50':'^NSEI','NIFTY NEXT 50':'^NSMIDCP','NIFTY 100':'^CNX100','NIFTY 200':'^CNX200','NIFTY 500':'^CRSLDX','NIFTY MIDCAP 50':'^NSEMDCP50','NIFTY MIDCAP 100':'^CNXMDCP','NIFTY MIDCAP 150':'^CNXMDCP150','NIFTY BANK':'^NSEBANK','NIFTY FINANCIAL SERVICES':'^NSEFIN','NIFTY IT':'^CNXIT','NIFTY HEALTHCARE':'^CNXHEALTH','NIFTY PHARMA':'^CNXPHARMA','NIFTY AUTO':'^CNXAUTO','NIFTY FMCG':'^CNXFMCG','NIFTY METAL':'^CNXMETAL','NIFTY MEDIA':'^CNXMEDIA','NIFTY REALTY':'^CNXREALTY','NIFTY PRIVATE BANK':'^CNXPVTBANK','NIFTY PSU BANK':'^CNXPSUBANK','NIFTY OIL & GAS':'^CNXENERGY','NIFTY CAPITAL GOODS':'^CNXCG','NIFTY CEMENT':'^CNXCEMENT','NIFTY INFRASTRUCTURE':'^CNXINFRA','NIFTY ENERGY':'^CNXENERGY','NIFTY COMMODITIES':'^CNXCOMMODITIES'};
const QUALITY:Record<string,number>={Diversified:78,'Large & Mid Cap':82,'Multi Asset':84,'Multi Cap':80,Infrastructure:78,'Banking & Financial':77,'Nifty 50':92,Healthcare:84,'Focused Equity':80,Children:80,'Small Cap':74,'Mid Cap':80,'Nifty Next 50':90,Gold:82,Value:85,ELSS:82,Services:78,Technology:86};
const HEADERS={'User-Agent':'Mozilla/5.0 (compatible; SmartMFDecisionTerminal/1.0)','Accept':'application/json,text/plain,*/*'};

async function fetchJson(url:string,extra:Record<string,string>={}):Promise<unknown>{const c=new AbortController();const t=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:{...HEADERS,...extra}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(t);}}
async function fetchText(url:string):Promise<string>{const c=new AbortController();const t=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:HEADERS});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text();}finally{clearTimeout(t);}}
function normalizeDate(v:string):string{const p=v.split('-');if(p.length!==3)return v;const months:Record<string,string>={Jan:'01',Feb:'02',Mar:'03',Apr:'04',May:'05',Jun:'06',Jul:'07',Aug:'08',Sep:'09',Oct:'10',Nov:'11',Dec:'12'};return `${p[2]}-${months[p[1]]??p[1]}-${p[0].padStart(2,'0')}`;}
function norm(v:string):string{return v.toUpperCase().replace(/&/g,' AND ').replace(/[^A-Z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function sma(p:Point[],n:number):number|null{return p.length>=n?p.slice(-n).reduce((a,x)=>a+x.value,0)/n:null;}
function periodReturn(p:Point[],days:number):number|null{if(p.length<2)return null;const end=p[p.length-1].value,start=p[Math.max(0,p.length-1-days)].value;return start>0?(end/start-1)*100:null;}
function returns(p:Point[]):Map<string,number>{const m=new Map<string,number>();for(let i=1;i<p.length;i++){if(p[i-1].value>0)m.set(p[i].date,(p[i].value/p[i-1].value-1)*100);}return m;}
function beta(xs:number[],ys:number[]):number|null{if(xs.length<30)return null;const mx=xs.reduce((a,b)=>a+b,0)/xs.length,my=ys.reduce((a,b)=>a+b,0)/ys.length;let cov=0,varY=0;for(let i=0;i<xs.length;i++){cov+=(xs[i]-mx)*(ys[i]-my);varY+=(ys[i]-my)**2;}return varY?Math.max(.1,Math.min(3,cov/varY)):null;}
function matchIndex(name:string,row:Record<string,unknown>):boolean{const a=norm(name),b=norm(String(row.index??row.indexName??row.name??''));return a===b||a===`${b} INDEX`||b===`${a} INDEX`||(a.length>8&&(a.includes(b)||b.includes(a)));}

async function getAmfi():Promise<Map<string,{nav:number;date:string}>>{const out=new Map<string,{nav:number;date:string}>();try{const raw=await fetchText('https://www.amfiindia.com/spages/NAVAll.txt');for(const line of raw.split(/\r?\n/)){const p=line.split(';');if(p.length<6)continue;const code=(p[0]??'').trim(),nav=Number((p[4]??'').trim()),date=(p[5]??'').trim();if(/^\d+$/.test(code)&&Number.isFinite(nav)&&date)out.set(code,{nav,date});}}catch{}return out;}
async function getFundHistory(code:string):Promise<Point[]>{try{const raw=await fetchJson(`https://api.mfapi.in/mf/${code}`);const data=raw as {data?:Array<{date?:string;nav?:string}>};return(Array.isArray(data.data)?data.data:[]).map(x=>({date:normalizeDate(String(x.date??'')),value:Number(x.nav)})).filter(x=>x.date&&Number.isFinite(x.value)).sort((a,b)=>a.date.localeCompare(b.date));}catch{return[];}}
async function getIndexHistory(symbol:string):Promise<Point[]>{try{const raw=await fetchJson(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=2y&interval=1d`);const data=raw as {chart?:{result?:Array<{timestamp?:number[];indicators?:{quote?:Array<{close?:Array<number|null>}>}}>} };const r=data.chart?.result?.[0];const ts=r?.timestamp??[],cl=r?.indicators?.quote?.[0]?.close??[];return ts.map((t,i)=>({date:new Date(t*1000).toISOString().slice(0,10),value:Number(cl[i])})).filter(x=>Number.isFinite(x.value));}catch{return[];}}
async function getNseRows():Promise<Record<string,unknown>[]> {try{const home=await fetch('https://www.nseindia.com/',{cache:'no-store',headers:HEADERS});const cookie=home.headers.get('set-cookie')?.split(';')[0]??'';const raw=await fetchJson('https://www.nseindia.com/api/allIndices',{'accept-language':'en-US,en;q=0.9','referer':'https://www.nseindia.com/market-data/live-market-indices',...(cookie?{cookie}:{})});const d=raw as {data?:unknown};return Array.isArray(d.data)?d.data.filter((x):x is Record<string,unknown>=>typeof x==='object'&&x!==null):[];}catch{return[];}}

function alignment(category:string,proxy:string):number{const s=proxy.toUpperCase();if(s.includes('IT')||s.includes('TELECOMMUNICATION'))return category==='Technology'?1:category==='Focused Equity'?.45:.35;if(s.includes('HEALTH')||s.includes('PHARMA')||s.includes('HOSPITAL'))return category==='Healthcare'?1:category==='Focused Equity'?.45:.35;if(s.includes('BANK')||s.includes('FINANCIAL')||s.includes('NBFC')||s.includes('INSURANCE'))return category==='Banking & Financial'?1:['Focused Equity','Value'].includes(category)?.5:.35;if(s.includes('SMALLCAP'))return category==='Small Cap'?1:['Multi Cap','Diversified'].includes(category)?.4:.25;if(s.includes('MIDCAP'))return category==='Mid Cap'?1:category==='Large & Mid Cap'?.7:['Multi Cap','Diversified'].includes(category)?.4:.25;if(s.includes('INFRA')||s.includes('CAPITAL GOODS')||s.includes('POWER')||s.includes('CEMENT')||s.includes('CONSTRUCTION'))return category==='Infrastructure'?1:['Diversified','Multi Cap','Large & Mid Cap'].includes(category)?.4:.25;if(s.includes('SERVICES'))return category==='Services'?1:['Diversified','Multi Cap','Large & Mid Cap'].includes(category)?.4:.25;if(s.includes('COMMODITIES'))return category==='Gold'?1:.15;if(s==='NIFTY 50')return category==='Nifty 50'?1:['Focused Equity','Diversified','Multi Cap','Large & Mid Cap','ELSS','Children','Value'].includes(category)?.45:.25;return .3;}
function strategic(h:Point[],quality:number){const nav=h.length?h[h.length-1].value:0,s20=sma(h,20),s50=sma(h,50),s100=sma(h,100),s200=sma(h,200),r1=periodReturn(h,21)??0,r3=periodReturn(h,63)??0,r6=periodReturn(h,126)??0,peak=h.length?Math.max(...h.map(x=>x.value)):nav,dd=peak>0?(nav/peak-1)*100:0;const trend=((nav>=(s50??nav)?1:0)+(nav>=(s200??nav)?1:0)+((s50??nav)>=(s200??nav)?1:0))/3*100;const consistency=[r1,r3,r6].filter(x=>x>=0).length/3*100;const returnScore=Math.max(0,Math.min(100,50+r1*1.5+r3*.6+r6*.3));const momentum=Math.max(0,Math.min(100,50+r1*3+r3*1.2));const drawdownQuality=Math.max(0,Math.min(100,50+Math.abs(Math.min(0,dd))*1.2));const score=quality*.25+trend*.30+returnScore*.20+drawdownQuality*.10+consistency*.10+momentum*.05;return{score:Math.max(0,Math.min(100,score)),nav,s20,s50,s100,s200,r1,r3,r6,dd,trend,momentum};}

export async function buildDashboard(strategicRaw:number,opportunityRaw:number){
 const total=(strategicRaw+opportunityRaw)||100;const sw=(Number.isFinite(strategicRaw)?strategicRaw:60)/total*100;const ow=(Number.isFinite(opportunityRaw)?opportunityRaw:40)/total*100;
 const [amfi,nseRows]=await Promise.all([getAmfi(),getNseRows()]);
 const indices:IndexRow[]=await Promise.all(INDEXES.map(async([name,group]):Promise<IndexRow>=>{const row=nseRows.find(x=>matchIndex(name,x));if(row){const value=Number(row.last??row.indexValue??row.value),change=Number(row.percentChange??row.percChange??row.changePercent??row.change);if(Number.isFinite(value)&&Number.isFinite(change))return {name,value,change,group,status:'LIVE',source:'NSE'};}const symbol=Y[name];if(symbol){const h=await getIndexHistory(symbol);if(h.length){const a=h[h.length-1],b=h.length>1?h[h.length-2]:null;return {name,value:a.value,change:b?((a.value/b.value)-1)*100:0,group,status:'LIVE',source:'YAHOO'};}}return {name,value:null,change:null,group,status:'UNAVAILABLE',source:'UNAVAILABLE'};}));
 const indexMap=new Map<string,IndexRow>();indices.forEach(x=>indexMap.set(x.name,x));
 const indexHistEntries=await Promise.all(INDEXES.filter(([name])=>Boolean(Y[name])).map(async([name])=>[name,await getIndexHistory(Y[name])] as [string,Point[]]));const indexHist=new Map<string,Point[]>(indexHistEntries);
 const fundHistEntries=await Promise.all(FUNDS.map(async f=>[f.code,await getFundHistory(f.code)] as [string,Point[]]));const fundHist=new Map<string,Point[]>(fundHistEntries);
 const funds=FUNDS.map(f=>{
  const h=fundHist.get(f.code)??[],latest=amfi.get(f.code),nav=latest?.nav??(h.length?h[h.length-1].value:null),previous=h.length>1?h[h.length-2].value:null,change=nav!=null&&previous!=null?(nav/previous-1)*100:null,st=strategic(h,QUALITY[f.category]??75);
  const live=f.proxies.map(p=>indexMap.get(p)).filter((x):x is IndexRow=>Boolean(x&&x.status==='LIVE'&&x.change!=null));
  const lead=live.length?live.reduce((a,b)=>(b.change??0)<(a.change??0)?b:a):null;const marketMove=live.length?live.reduce((s,x)=>s+(x.change??0),0)/live.length:null;const falling=live.filter(x=>(x.change??0)<0).length;const confirmation=live.length?falling/live.length:0;const align=alignment(f.category,lead?.name??'');
  const marketFall=marketMove!=null&&marketMove<0?Math.min(100,Math.abs(marketMove)*38):0;const leadFall=lead?.change!=null&&lead.change<0?Math.min(100,Math.abs(lead.change)*45):0;const drawdown=Math.max(0,Math.min(100,50+Math.abs(Math.min(0,st.dd))*1.5));const relative=Math.max(0,Math.min(100,50+st.r1*3+st.r3*1.2));
  const daily=Math.max(0,Math.min(100,marketFall*.25+leadFall*.30*align+drawdown*.15+st.trend*.20+relative*.10));
  const structural=st.nav>0&&st.s50!=null&&st.s200!=null&&st.nav<st.s200&&st.s50<st.s200&&st.r3<0;const healthy=!structural&&confirmation>=.33&&marketMove!=null&&marketMove<0&&st.trend>=50;
  const final=Math.max(0,Math.min(100,st.score*sw/100+daily*ow/100));const classification=structural?'STRUCTURAL BREAKDOWN':healthy?'HEALTHY CORRECTION':'NEUTRAL / WAIT';let signal=structural?'AVOID TODAY':final>=72?'BUY ON DIP':final>=55?'SIP / ACCUMULATE':final>=40?'WATCH':'WAIT';
  let fundBeta:number|null=null;const proxyHistory=f.proxies.map(p=>indexHist.get(p)).find(x=>Boolean(x&&x.length>30));if(proxyHistory&&h.length>30){const fr=returns(h),ir=returns(proxyHistory),xs:number[]=[],ys:number[]=[];fr.forEach((v,d)=>{const q=ir.get(d);if(q!=null){xs.push(v);ys.push(q);}});fundBeta=beta(xs,ys);}
  const expected=marketMove!=null&&fundBeta!=null?marketMove*fundBeta:null;const base=previous??(nav!=null&&change!=null?nav/(1+change/100):null);const estimatedNav=base!=null&&expected!=null?base*(1+expected/100):null;const risk=Math.max(0,Math.min(100,Math.abs(Math.min(0,st.dd))*1.8+(100-st.trend)*.5));const confidence=Math.min(100,55+confirmation*25+(live.length/Math.max(1,f.proxies.length))*15);
  return {code:f.code,name:f.name,category:f.category,nav,previousNav:previous,change,date:latest?.date??(h.length?h[h.length-1].date:null),status:nav!=null?'LIVE':'UNAVAILABLE',sectorMove:marketMove,leadSector:lead?.name??'NO LIVE MAPPED INDEX',leadMove:lead?.change??null,relativeCorrection:expected!=null&&marketMove!=null?expected-marketMove:null,confirmation,mappedLive:live.length,mappedTotal:f.proxies.length,sectorScore:Number((Math.max(marketFall,leadFall)*align).toFixed(1)),relativeScore:Number(relative.toFixed(1)),confirmationScore:Number((confirmation*100).toFixed(1)),qualityScore:QUALITY[f.category]??75,score:Number(final.toFixed(1)),opportunityScore:Number(final.toFixed(1)),riskScore:Number(risk.toFixed(1)),confidenceScore:Number(confidence.toFixed(1)),signal,reason:structural?'Structural breakdown: NAV below 200DMA + 50DMA below 200DMA + negative 3M return.':healthy?`${lead?.name??'Mapped proxy'} is weak while fund trend remains intact — Healthy Correction.`:`Final score = ${sw.toFixed(0)}% Strategic + ${ow.toFixed(0)}% Daily NAV Opportunity.`,historicalCheapness:Number(drawdown.toFixed(1)),volatility:null,drawdown:Number(st.dd.toFixed(1)),beta:fundBeta==null?null:Number(fundBeta.toFixed(2)),dataConfidence:Math.round(live.length/Math.max(1,f.proxies.length)*100),strategicScore:Number(st.score.toFixed(1)),dailyNavOpportunityScore:Number(daily.toFixed(1)),finalDailyScore:Number(final.toFixed(1)),classification,trend:{navVs50:st.s50!=null?st.nav>=st.s50:null,navVs200:st.s200!=null?st.nav>=st.s200:null,sma50Vs200:st.s50!=null&&st.s200!=null?st.s50>=st.s200:null,s20:st.s20,s50:st.s50,s100:st.s100,s200:st.s200},momentum:{r1:Number(st.r1.toFixed(2)),r3:Number(st.r3.toFixed(2)),r6:Number(st.r6.toFixed(2)),relativeStrength:Number(relative.toFixed(1))},estimatedNav,estimatedChange:expected,proxyBasket:true};
 });
 funds.sort((a,b)=>b.finalDailyScore-a.finalDailyScore);
 const live=indices.filter(x=>x.status==='LIVE'),sector=indices.filter(x=>x.group==='SECTORAL'),greenSector=sector.filter(x=>(x.change??0)>0).length,breadth=sector.length?greenSector/sector.length*100:0,up=live.length?live.filter(x=>(x.change??0)>0).length/live.length*100:0,regime=breadth>=55&&up>=50?'RISK ON':'RISK OFF';
 const sectors=indices.filter(x=>x.group!=='BROAD').map(x=>({name:x.name,value:x.value,change:x.change,status:x.status,severity:x.change!=null&&x.change<0?'WEAK':'STRONG'}));
 return {updatedAt:new Date().toISOString(),weights:{strategic:sw,opportunity:ow},funds,indices,sectors,summary:{trackedFunds:FUNDS.length,liveFunds:funds.filter(x=>x.status==='LIVE').length,liveIndices:live.length,fallingIndices:live.filter(x=>(x.change??0)<0).length,buySignals:funds.filter(x=>x.signal==='BUY ON DIP').length,accumulateSignals:funds.filter(x=>x.signal==='SIP / ACCUMULATE').length,breadth:Number(breadth.toFixed(1)),regime,regimeNote:regime==='RISK ON'?'Continue SIP + deploy corrections selectively.':'Continue core SIP, reduce tactical allocation, avoid chasing sector funds.',dataConfidence:Math.round(live.length/Math.max(1,indices.length)*100),coverage:`${live.length}/${indices.length}`},disclaimer:'Probability-based signals only. Intraday mutual-fund NAV is not available; mapped market weakness is an estimate of likely closing-NAV pressure. Applicable NAV depends on cut-off and fund-realisation conditions. Proxy mapping is an approximation, not actual holdings. Free/unofficial data may be delayed or unavailable.'};
}
