import {NextResponse} from 'next/server';
export const dynamic='force-dynamic';
export const revalidate=0;

const funds=[
['120843','Quant Flexi Cap Fund Direct Growth','Diversified'],['120826','Quant Large and Mid Cap Fund Direct Growth','Large & Mid Cap'],['120821','Quant Multi Asset Fund Direct Growth','Multi Asset'],['120823','Quant Multi Cap Fund Direct Growth','Multi Cap'],['120833','Quant Infrastructure Fund Direct Growth','Infrastructure'],['151791','Quant BFSI Fund Direct Growth','Banking & Financial'],['119827','SBI Nifty 50 Index Fund Direct Growth','Nifty 50'],['119783','SBI Healthcare Opportunities Fund Direct Growth','Healthcare'],['119727','SBI Focused Equity Fund Direct Growth','Focused Equity'],['148490',"SBI Children's Benefit Fund Direct Growth",'Children'],['147946','Bandhan Small Cap Fund Direct Growth','Small Cap'],['118989','HDFC Mid Cap Opportunities Fund Direct Growth','Mid Cap'],['143341','UTI Nifty Next 50 Index Fund Direct Growth','Nifty Next 50'],['150714','UTI Gold ETF FoF Direct Growth','Gold'],['125497','SBI Small Cap Fund Direct Growth','Small Cap'],['120586','ICICI Prudential Value Discovery Fund Direct Growth','Value'],['120503','Axis ELSS Tax Saver Fund Direct Growth','ELSS'],['144835','Sundaram Services Fund Direct Growth','Services'],['135800','Tata Digital India Fund Direct Growth','Technology']
] as const;
const indices=[['NIFTY 50','%5ENSEI'],['NIFTY NEXT 50','%5ENSEMDCP50.NS'],['NIFTY BANK','%5ENSEBANK'],['NIFTY IT','%5ECNXTIT'],['NIFTY HEALTHCARE','%5ECNXRHEALTH'],['NIFTY INFRA','%5ECNXINFRA'],['NIFTY SERVICES','%5ECNXNIFTY']];
async function json(url:string){const r=await fetch(url,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(String(r.status));return r.json()}
async function fund(code:string){try{const j=await json(`https://api.mfapi.in/mf/${code}/latest`);const d=j.data||[];const nav=Number(d[0]?.nav||0), prev=Number(d[1]?.nav||nav);const ch=prev?((nav-prev)/prev)*100:0;return {nav,date:d[0]?.date||null,change:ch,status:'LIVE'};}catch{return {nav:null,date:null,change:null,status:'UNAVAILABLE'}}}
async function index(symbol:string){try{const j=await json(`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?range=5d&interval=1d`);const r=j.chart.result?.[0];const q=r?.indicators?.quote?.[0];const c=(q?.close||[]).filter((x:any)=>x!=null);const last=Number(c.at(-1));const prev=Number(c.at(-2)||last);return {value:last,change:prev?((last-prev)/prev)*100:0,status:'LIVE'};}catch{return {value:null,change:null,status:'UNAVAILABLE'}}}
export async function GET(){
 const [fundData,indexData]=await Promise.all([Promise.all(funds.map(async f=>({...f, data:await fund(f[0])}))),Promise.all(indices.map(async x=>({...x, data:await index(x[1])}))) ]);
 const enriched=fundData.map(f=>{const daily=f.data.change??0;const score=Math.max(0,Math.min(100,50+(-daily*7)+(daily<0?12:0)));let signal=score>=75?'BUY':score>=62?'ACCUMULATE':score>=48?'WATCH':'WAIT';if(f[2]==='Gold')signal=score>=62?'ACCUMULATE':'WATCH';return {code:f[0],name:f[1],category:f[2],...f.data,score:Number(score.toFixed(1)),signal}}).sort((a,b)=>b.score-a.score);
 return NextResponse.json({updatedAt:new Date().toISOString(),funds:enriched,indices:indexData.map(x=>({name:x[0],...x.data})),source:'MFAPI + Yahoo Finance',note:'Intraday market moves are indicative; mutual-fund NAV is published end-of-day.'},{headers:{'Cache-Control':'no-store'}})
}