import {NextResponse} from 'next/server';

export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const maxDuration = 60;

type Group = 'BROAD' | 'SECTORAL' | 'THEMATIC';
type FundConfig = readonly [string, string, string, string[]];
type FundSnapshot = {nav:number|null;previousNav:number|null;change:number|null;date:string|null;status:'LIVE'|'UNAVAILABLE';source:'AMFI'|'MFAPI'|'UNAVAILABLE'};
type IndexSnapshot = {name:string;value:number|null;change:number|null;status:'LIVE'|'UNAVAILABLE';group:Group;source:'NSE'|'NIFTY'|'YAHOO'|'UNAVAILABLE'};
type IndexDef = {name:string;group:Group};

const funds:FundConfig[]=[
 ['120843','Quant Flexi Cap Fund Direct Growth','Diversified',['NIFTY 50','NIFTY SERVICES SECTOR']],
 ['120826','Quant Large and Mid Cap Fund Direct Growth','Large & Mid Cap',['NIFTY 50','NIFTY NEXT 50','NIFTY MIDCAP 150']],
 ['120821','Quant Multi Asset Fund Direct Growth','Multi Asset',['NIFTY 50','NIFTY BANK','NIFTY 500']],
 ['120823','Quant Multi Cap Fund Direct Growth','Multi Cap',['NIFTY 50','NIFTY NEXT 50','NIFTY MIDCAP 150']],
 ['120833','Quant Infrastructure Fund Direct Growth','Infrastructure',['NIFTY INFRASTRUCTURE','NIFTY CAPITAL GOODS','NIFTY CONSTRUCTION','NIFTY CEMENT','NIFTY POWER']],
 ['151791','Quant BFSI Fund Direct Growth','Banking & Financial',['NIFTY BANK','NIFTY FINANCIAL SERVICES','NIFTY FINANCIAL SERVICES 25/50','NIFTY FINANCIAL SERVICES EX-BANK','NIFTY PRIVATE BANK','NIFTY PSU BANK','NIFTY NBFC','NIFTY INSURANCE','NIFTY HOUSING FINANCE']],
 ['119827','SBI Nifty 50 Index Fund Direct Growth','Nifty 50',['NIFTY 50']],
 ['119783','SBI Healthcare Opportunities Fund Direct Growth','Healthcare',['NIFTY HEALTHCARE','NIFTY PHARMA','NIFTY HOSPITALS','NIFTY500 HEALTHCARE','NIFTY MIDSMALL HEALTHCARE']],
 ['119727','SBI Focused Equity Fund Direct Growth','Focused Equity',['NIFTY 50','NIFTY FINANCIAL SERVICES','NIFTY IT']],
 ['148490',"SBI Children's Benefit Fund Direct Growth",'Children',['NIFTY 50','NIFTY CONSUMER SERVICES']],
 ['147946','Bandhan Small Cap Fund Direct Growth','Small Cap',['NIFTY SMALLCAP 50','NIFTY SMALLCAP 100','NIFTY SMALLCAP 250','NIFTY MIDSMALLCAP 400']],
 ['118989','HDFC Mid Cap Opportunities Fund Direct Growth','Mid Cap',['NIFTY MIDCAP 50','NIFTY MIDCAP 100','NIFTY MIDCAP 150','NIFTY NEXT 50']],
 ['143341','UTI Nifty Next 50 Index Fund Direct Growth','Nifty Next 50',['NIFTY NEXT 50']],
 ['150714','UTI Gold ETF FoF Direct Growth','Gold',['NIFTY COMMODITIES']],
 ['125497','SBI Small Cap Fund Direct Growth','Small Cap',['NIFTY SMALLCAP 50','NIFTY SMALLCAP 100','NIFTY SMALLCAP 250','NIFTY MIDSMALLCAP 400']],
 ['120586','ICICI Prudential Value Discovery Fund Direct Growth','Value',['NIFTY 50','NIFTY FINANCIAL SERVICES','NIFTY PRIVATE BANK','NIFTY REALTY','NIFTY REITS & REALTY']],
 ['120503','Axis ELSS Tax Saver Fund Direct Growth','ELSS',['NIFTY 50']],
 ['144835','Sundaram Services Fund Direct Growth','Services',['NIFTY SERVICES SECTOR','NIFTY CONSUMER SERVICES','NIFTY COMMERCIAL & TRANSPORT SERVICES']],
 ['135800','Tata Digital India Fund Direct Growth','Technology',['NIFTY IT','NIFTY MIDSMALL IT & TELECOM','NIFTY TELECOMMUNICATIONS']]
];

const indexNames:IndexDef[]=[
 ...['NIFTY 50','NIFTY NEXT 50','NIFTY 100','NIFTY 200','NIFTY 500','NIFTY MIDCAP 50','NIFTY MIDCAP 100','NIFTY MIDCAP 150','NIFTY SMALLCAP 50','NIFTY SMALLCAP 100','NIFTY SMALLCAP 250','NIFTY MIDSMALLCAP 400'].map(name=>({name,group:'BROAD' as Group})),
 ...['NIFTY BANK','NIFTY FINANCIAL SERVICES','NIFTY FINANCIAL SERVICES 25/50','NIFTY FINANCIAL SERVICES EX-BANK','NIFTY IT','NIFTY HEALTHCARE','NIFTY PHARMA','NIFTY AUTO','NIFTY FMCG','NIFTY METAL','NIFTY MEDIA','NIFTY REALTY','NIFTY PRIVATE BANK','NIFTY PSU BANK','NIFTY OIL & GAS','NIFTY CONSUMER DURABLES','NIFTY CAPITAL GOODS','NIFTY POWER','NIFTY TELECOMMUNICATIONS','NIFTY RETAIL','NIFTY INSURANCE','NIFTY NBFC','NIFTY CEMENT','NIFTY CHEMICALS','NIFTY CONSTRUCTION','NIFTY CONSUMER SERVICES','NIFTY COMMERCIAL & TRANSPORT SERVICES','NIFTY HOSPITALS','NIFTY HOUSING FINANCE','NIFTY REITS & REALTY','NIFTY500 HEALTHCARE','NIFTY MIDSMALL FINANCIAL SERVICES','NIFTY MIDSMALL HEALTHCARE','NIFTY MIDSMALL IT & TELECOM'].map(name=>({name,group:'SECTORAL' as Group})),
 ...['NIFTY INFRASTRUCTURE','NIFTY SERVICES SECTOR','NIFTY ENERGY','NIFTY COMMODITIES'].map(name=>({name,group:'THEMATIC' as Group}))
];

const aliases:Record<string,string[]>={
 'NIFTY 50':['NIFTY 50','NIFTY50','NIFTY 50 TRI'],'NIFTY NEXT 50':['NIFTY NEXT 50','NIFTY NEXT50','NIFTY NEXT 50 TRI'],'NIFTY 100':['NIFTY 100','NIFTY100'],'NIFTY 200':['NIFTY 200','NIFTY200'],'NIFTY 500':['NIFTY 500','NIFTY500'],
 'NIFTY MIDCAP 50':['NIFTY MIDCAP 50','NIFTY MIDCAP50'],'NIFTY MIDCAP 100':['NIFTY MIDCAP 100','NIFTY MIDCAP100'],'NIFTY MIDCAP 150':['NIFTY MIDCAP 150','NIFTY MIDCAP150'],
 'NIFTY SMALLCAP 50':['NIFTY SMALLCAP 50','NIFTY SMALL CAP 50'],'NIFTY SMALLCAP 100':['NIFTY SMALLCAP 100','NIFTY SMALL CAP 100'],'NIFTY SMALLCAP 250':['NIFTY SMALLCAP 250','NIFTY SMALL CAP 250'],
 'NIFTY MIDSMALLCAP 400':['NIFTY MIDSMALLCAP 400','NIFTY MIDSMALLCAP400','NIFTY MIDSMALLCAP 400 TRI'],
 'NIFTY FINANCIAL SERVICES 25/50':['NIFTY FINANCIAL SERVICES 25/50','NIFTY FINSRV25 50','NIFTY FINSRV25 50 INDEX'],'NIFTY FINANCIAL SERVICES EX-BANK':['NIFTY FINANCIAL SERVICES EX-BANK','NIFTY FINANCIAL SERVICES EX BANK'],
 'NIFTY OIL & GAS':['NIFTY OIL & GAS','NIFTY OIL AND GAS','NIFTY OIL AND GAS INDEX'],'NIFTY CONSUMER DURABLES':['NIFTY CONSUMER DURABLES','NIFTY CONSUMER DURABLE'],'NIFTY TELECOMMUNICATIONS':['NIFTY TELECOMMUNICATIONS','NIFTY TELECOM'],
 'NIFTY REITS & REALTY':['NIFTY REITS & REALTY','NIFTY REITS AND REALTY','NIFTY REITS & REALTY INDEX'],'NIFTY500 HEALTHCARE':['NIFTY500 HEALTHCARE','NIFTY 500 HEALTHCARE','NIFTY500 HEALTHCARE INDEX'],
 'NIFTY MIDSMALL FINANCIAL SERVICES':['NIFTY MIDSMALL FINANCIAL SERVICES','NIFTY MIDSMALL FINANCIAL SERVICES INDEX'],'NIFTY MIDSMALL HEALTHCARE':['NIFTY MIDSMALL HEALTHCARE','NIFTY MIDSMALL HEALTHCARE INDEX'],
 'NIFTY MIDSMALL IT & TELECOM':['NIFTY MIDSMALL IT & TELECOM','NIFTY MIDSMALL IT AND TELECOM','NIFTY MIDSMALL IT & TELECOM INDEX'],'NIFTY COMMERCIAL & TRANSPORT SERVICES':['NIFTY COMMERCIAL & TRANSPORT SERVICES','NIFTY COMMERCIAL AND TRANSPORT SERVICES','NIFTY COMMERCIAL & TRANSPORT SERVICES INDEX'],
 'NIFTY INFRASTRUCTURE':['NIFTY INFRASTRUCTURE','NIFTY INFRASTRUCTURE INDEX','NIFTY INFRA'],'NIFTY SERVICES SECTOR':['NIFTY SERVICES SECTOR','NIFTY SERVICES SECTOR INDEX','NIFTY SERVICES'],
 'NIFTY CAPITAL GOODS':['NIFTY CAPITAL GOODS','NIFTY CAPITAL GOODS INDEX'],'NIFTY CONSTRUCTION':['NIFTY CONSTRUCTION','NIFTY CONSTRUCTION INDEX'],'NIFTY CONSUMER SERVICES':['NIFTY CONSUMER SERVICES','NIFTY CONSUMER SERVICES INDEX'],
 'NIFTY HOSPITALS':['NIFTY HOSPITALS','NIFTY HOSPITALS INDEX'],'NIFTY HOUSING FINANCE':['NIFTY HOUSING FINANCE','NIFTY HOUSING FINANCE INDEX'],'NIFTY INSURANCE':['NIFTY INSURANCE','NIFTY INSURANCE INDEX'],'NIFTY NBFC':['NIFTY NBFC','NIFTY NBFC INDEX'],'NIFTY POWER':['NIFTY POWER','NIFTY POWER INDEX'],'NIFTY RETAIL':['NIFTY RETAIL','NIFTY RETAIL INDEX']
};

const knownYahoo:Record<string,string>={'NIFTY 50':'^NSEI','NIFTY NEXT 50':'^NSMIDCP','NIFTY 100':'^CNX100','NIFTY 200':'^CNX200','NIFTY 500':'^CRSLDX','NIFTY MIDCAP 50':'^NSEMDCP50','NIFTY MIDCAP 100':'^CNXMDCP','NIFTY MIDCAP 150':'^NSEMDCP150','NIFTY BANK':'^NSEBANK','NIFTY FINANCIAL SERVICES':'^NSEFIN','NIFTY IT':'^CNXIT','NIFTY PHARMA':'^CNXPHARMA','NIFTY AUTO':'^CNXAUTO','NIFTY FMCG':'^CNXFMCG','NIFTY METAL':'^CNXMETAL','NIFTY MEDIA':'^CNXMEDIA','NIFTY REALTY':'^CNXREALTY','NIFTY PSU BANK':'^CNXPSUBANK','NIFTY INFRASTRUCTURE':'^CNXINFRA','NIFTY CEMENT':'^CNXCEMENT','NIFTY ENERGY':'^CNXENERGY'};
const headers:Record<string,string>={'User-Agent':'Mozilla/5.0 (compatible; AkashMutualFunds/3.0)','Accept':'application/json,text/plain,*/*'};

async function json(url:string,extra:Record<string,string>={}):Promise<unknown>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),9000);try{const r=await fetch(url,{cache:'no-store',signal:controller.signal,headers:{...headers,...extra}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}finally{clearTimeout(timeout);}}
async function text(url:string):Promise<string>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),9000);try{const r=await fetch(url,{cache:'no-store',signal:controller.signal,headers:{...headers,Accept:'text/plain,*/*'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text();}finally{clearTimeout(timeout);}}

type AmfiNav={nav:number;date:string};
async function fetchAmfiNavs():Promise<Map<string,AmfiNav>>{const map=new Map<string,AmfiNav>();try{const raw=await text('https://www.amfiindia.com/spages/NAVAll.txt');for(const line of raw.split(/\r?\n/)){const p=line.split(';');if(p.length<6)continue;const code=p[0].trim(),nav=Number(p[4]?.trim()),date=p[5]?.trim();if(/^\d+$/.test(code)&&Number.isFinite(nav)&&date)map.set(code,{nav,date});}}catch{}return map;}
async function mfapiHistory(code:string):Promise<{nav:number;previousNav:number;date:string}|null>{for(let attempt=0;attempt<2;attempt++){try{const j=await json(`https://api.mfapi.in/mf/${code}`) as {data?:Array<{nav?:string;date?:string}>};const d=Array.isArray(j.data)?j.data:[];const nav=Number(d[0]?.nav),previousNav=Number(d[1]?.nav);if(Number.isFinite(nav)&&Number.isFinite(previousNav)&&previousNav!==0)return{nav,previousNav,date:d[0]?.date??''};}catch{}}return null;}
async function fundSnapshot(code:string,amfi:Map<string,AmfiNav>):Promise<FundSnapshot>{const current=amfi.get(code);const history=await mfapiHistory(code);if(current)return{nav:current.nav,previousNav:history?.previousNav??null,change:history?((current.nav-history.previousNav)/history.previousNav)*100:null,date:current.date||history?.date||null,status:'LIVE',source:'AMFI'};if(history)return{nav:history.nav,previousNav:history.previousNav,change:((history.nav-history.previousNav)/history.previousNav)*100,date:history.date,status:'LIVE',source:'MFAPI'};return{nav:null,previousNav:null,change:null,date:null,status:'UNAVAILABLE',source:'UNAVAILABLE'};}

function norm(value:string):string{return value.toUpperCase().replace(/&/g,' AND ').replace(/[^A-Z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function namesFor(target:string):string[]{return [target,...(aliases[target]??[])].map(norm);}
function rowMatch(target:string,rows:Array<Record<string,unknown>>):{value:number;change:number}|null{const names=namesFor(target);const candidates=rows.filter(row=>typeof row.index==='string');let row=candidates.find(item=>names.includes(norm(String(item.index))));if(!row)row=candidates.find(item=>{const n=norm(String(item.index));return names.some(name=>n===name||n===`${name} INDEX`||name===`${n} INDEX`);});if(!row)row=candidates.find(item=>{const n=norm(String(item.index));return names.some(name=>name.length>=8&&(n.includes(name)||name.includes(n)));});const value=Number(row?.last),change=Number(row?.percentChange);return row&&Number.isFinite(value)&&Number.isFinite(change)?{value,change}:null;}
function liveWatchMatch(target:string,rows:Array<Record<string,unknown>>):{value:number;change:number}|null{const names=namesFor(target);for(const row of rows){const n=norm(String(row.indexName??row.name??row.index??row.indexNameFull??''));if(!names.some(name=>n===name||n===`${name} INDEX`||name===`${n} INDEX`||(name.length>=8&&(n.includes(name)||name.includes(n)))))continue;const value=Number(row.last??row.indexValue??row.value??row.close??row.currentValue),change=Number(row.percentChange??row.percChange??row.changePercent??row.change);if(Number.isFinite(value)&&Number.isFinite(change))return{value,change};}return null;}

async function getAllNseIndices():Promise<Array<Record<string,unknown>>>{try{const home=await fetch('https://www.nseindia.com/',{cache:'no-store',headers});const cookie=home.headers.get('set-cookie')??'';const data=await json('https://www.nseindia.com/api/allIndices',{'accept-language':'en-US,en;q=0.9',referer:'https://www.nseindia.com/market-data/live-market-indices',...(cookie?{cookie:cookie.split(';')[0]}:{})}) as {data?:unknown};return Array.isArray(data.data)?data.data.filter((row):row is Record<string,unknown>=>typeof row==='object'&&row!==null):[];}catch{try{const data=await json('https://www.nseindia.com/api/allIndices',{'accept-language':'en-US,en;q=0.9',referer:'https://www.nseindia.com/market-data/live-market-indices'}) as {data?:unknown};return Array.isArray(data.data)?data.data.filter((row):row is Record<string,unknown>=>typeof row==='object'&&row!==null):[];}catch{return[];}}}
async function getNiftyLiveWatch():Promise<Array<Record<string,unknown>>>{try{const data=await json('https://iislliveblob.niftyindices.com/jsonfiles/LiveIndicesWatch.json') as {data?:unknown}|unknown[];const rows=Array.isArray(data)?data:data.data;return Array.isArray(rows)?rows.filter((row):row is Record<string,unknown>=>typeof row==='object'&&row!==null):[];}catch{return[];}}
async function yahooChart(symbol:string):Promise<{value:number;change:number}|null>{try{const data=await json(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=5d&interval=1d`) as {chart?:{result?:Array<{indicators?:{quote?:Array<{close?:Array<number|null>}>}}>} };const closes=(data.chart?.result?.[0]?.indicators?.quote?.[0]?.close??[]).filter((value):value is number=>typeof value==='number');const value=Number(closes.at(-1)),previous=Number(closes.at(-2));if(!Number.isFinite(value))return null;return{value,change:Number.isFinite(previous)&&previous!==0?((value-previous)/previous)*100:0};}catch{return null;}}
async function yahooSearch(name:string):Promise<string|null>{try{const data=await json(`https://query1.finance.yahoo.com/v1/finance/search?q=${encodeURIComponent(name)}&quotesCount=10&newsCount=0`) as {quotes?:Array<Record<string,unknown>>};const quotes=Array.isArray(data.quotes)?data.quotes:[];const exact=quotes.find(q=>q.quoteType==='INDEX'&&typeof q.symbol==='string'&&norm(String(q.shortname??q.longname??q.symbol)).includes(norm(name)));if(exact&&typeof exact.symbol==='string')return exact.symbol;const any=quotes.find(q=>q.quoteType==='INDEX'&&typeof q.symbol==='string');return any&&typeof any.symbol==='string'?any.symbol:null;}catch{return null;}}
async function getIndex(target:IndexDef,nseRows:Array<Record<string,unknown>>,niftyRows:Array<Record<string,unknown>>):Promise<IndexSnapshot>{const nse=rowMatch(target.name,nseRows);if(nse)return{...target,...nse,status:'LIVE',source:'NSE'};const nifty=liveWatchMatch(target.name,niftyRows);if(nifty)return{...target,...nifty,status:'LIVE',source:'NIFTY'};const known=knownYahoo[target.name];if(known){const quote=await yahooChart(known);if(quote)return{...target,...quote,status:'LIVE',source:'YAHOO'};}const discovered=await yahooSearch(target.name);if(discovered){const quote=await yahooChart(discovered);if(quote)return{...target,...quote,status:'LIVE',source:'YAHOO'};}return{...target,value:null,change:null,status:'UNAVAILABLE',source:'UNAVAILABLE'};}
function clamp(value:number,min:number,max:number):number{return Math.min(max,Math.max(min,value));}
const quality:Record<string,number>={'Diversified':18,'Large & Mid Cap':17,'Multi Asset':18,'Multi Cap':17,'Infrastructure':15,'Banking & Financial':15,'Nifty 50':15,'Healthcare':17,'Focused Equity':15,'Children':14,'Small Cap':14,'Mid Cap':17,'Nifty Next 50':16,'Gold':13,'Value':18,'ELSS':16,'Services':15,'Technology':16};

type Opportunity={code:string;name:string;category:string;nav:number|null;previousNav:number|null;change:number|null;date:string|null;status:string;sectorMove:number|null;leadSector:string;leadMove:number|null;relativeCorrection:number|null;confirmation:number;mappedLive:number;mappedTotal:number;sectorScore:number;relativeScore:number;confirmationScore:number;qualityScore:number;score:number;signal:'BUY'|'ACCUMULATE'|'WATCH'|'WAIT';reason:string;mappedIndexes:Array<{name:string;change:number|null;status:string}>};
function scoreFund(config:FundConfig,snapshot:FundSnapshot,indexMap:Map<string,IndexSnapshot>):Opportunity{const[code,name,category,mapped]=config;const mappedIndexes=mapped.map(item=>indexMap.get(item)).filter((item):item is IndexSnapshot=>Boolean(item));const liveMapped=mappedIndexes.filter(item=>item.change!=null);const moves=liveMapped.map(item=>Number(item.change)).filter(Number.isFinite);const sectorMove=moves.length?moves.reduce((sum,value)=>sum+value,0)/moves.length:null;const lead=liveMapped.slice().sort((a,b)=>(a.change??0)-(b.change??0))[0];const negativeCount=moves.filter(move=>move<0).length;const confirmation=moves.length?negativeCount/moves.length:0;const relativeCorrection=snapshot.change!=null&&sectorMove!=null?snapshot.change-sectorMove:null;const sectorScore=sectorMove==null?0:clamp((-sectorMove/2)*35,0,35);const relativeScore=relativeCorrection==null?0:clamp((-relativeCorrection/1.5)*25,0,25);const confirmationScore=confirmation*20;const qualityScore=quality[category]??14;const score=Math.round(clamp(sectorScore+relativeScore+confirmationScore+qualityScore,0,100)*10)/10;let signal:Opportunity['signal']='WAIT';if(score>=75&&(sectorMove??0)<=-0.75&&confirmation>=0.5)signal='BUY';else if(score>=60&&(sectorMove??0)<=-0.4&&confirmation>=0.4)signal='ACCUMULATE';else if(score>=45)signal='WATCH';const reason=lead?`${lead.name} ${lead.change!>=0?'+':''}${lead.change!.toFixed(2)}% • ${negativeCount}/${moves.length} mapped indexes weak`:'Mapped index feed unavailable';return{code,name,category,nav:snapshot.nav,previousNav:snapshot.previousNav,change:snapshot.change,date:snapshot.date,status:snapshot.status,sectorMove,leadSector:lead?.name??mapped[0]??'Mapped index',leadMove:lead?.change??null,relativeCorrection,confirmation,mappedLive:liveMapped.length,mappedTotal:mapped.length,sectorScore:Math.round(sectorScore*10)/10,relativeScore:Math.round(relativeScore*10)/10,confirmationScore:Math.round(confirmationScore*10)/10,qualityScore,score,signal,reason,mappedIndexes:mappedIndexes.map(item=>({name:item.name,change:item.change,status:item.status}))};}

export async function GET():Promise<NextResponse>{const[amfi,nseRows,niftyRows]=await Promise.all([fetchAmfiNavs(),getAllNseIndices(),getNiftyLiveWatch()]);const indices:IndexSnapshot[]=await Promise.all(indexNames.map(index=>getIndex(index,nseRows,niftyRows)));const indexMap=new Map(indices.map(index=>[index.name,index]));const snapshots=await Promise.all(funds.map(([code])=>fundSnapshot(code,amfi)));const opportunities=funds.map((config,i)=>scoreFund(config,snapshots[i],indexMap)).sort((a,b)=>b.score-a.score);const sectors=indices.filter(index=>index.group!=='BROAD').map(index=>({name:index.name,value:index.value,change:index.change,status:index.status,severity:index.change!=null&&index.change<-1?'HIGH':index.change!=null&&index.change<0?'MEDIUM':'LOW'})).sort((a,b)=>(a.change??999)-(b.change??999));const liveFunds=opportunities.filter(fund=>fund.status==='LIVE').length;const liveIndices=indices.filter(index=>index.status==='LIVE').length;const fallingIndices=indices.filter(index=>(index.change??0)<0).length;const buySignals=opportunities.filter(fund=>fund.signal==='BUY').length;const accumulateSignals=opportunities.filter(fund=>fund.signal==='ACCUMULATE').length;return NextResponse.json({updatedAt:new Date().toISOString(),funds:opportunities,indices,sectors,summary:{trackedFunds:funds.length,liveFunds,liveIndices,fallingIndices,buySignals,accumulateSignals}},{headers:{'Cache-Control':'no-store','X-Index-Coverage':`${liveIndices}/${indices.length}`,'X-Fund-Coverage':`${liveFunds}/${funds.length}`}});}
