import {NextResponse} from 'next/server';
export const dynamic='force-dynamic'; export const revalidate=0; export const maxDuration=60;
const funds=[['120843','Quant Flexi Cap Fund Direct Growth'],['120826','Quant Large and Mid Cap Fund Direct Growth'],['120821','Quant Multi Asset Fund Direct Growth'],['120823','Quant Multi Cap Fund Direct Growth'],['120833','Quant Infrastructure Fund Direct Growth'],['151791','Quant BFSI Fund Direct Growth'],['119827','SBI Nifty 50 Index Fund Direct Growth'],['119783','SBI Healthcare Opportunities Fund Direct Growth'],['119727','SBI Focused Equity Fund Direct Growth'],['148490',"SBI Children's Benefit Fund Direct Growth"],['147946','Bandhan Small Cap Fund Direct Growth'],['118989','HDFC Mid Cap Opportunities Fund Direct Growth'],['143341','UTI Nifty Next 50 Index Fund Direct Growth'],['150714','UTI Gold ETF FoF Direct Growth'],['125497','SBI Small Cap Fund Direct Growth'],['120586','ICICI Prudential Value Discovery Fund Direct Growth'],['120503','Axis ELSS Tax Saver Fund Direct Growth'],['144835','Sundaram Services Fund Direct Growth'],['135800','Tata Digital India Fund Direct Growth']] as const;
type Point={date:string;nav:number};
async function history(code:string):Promise<Point[]>{const r=await fetch(`https://api.mfapi.in/mf/${code}`,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(`MFAPI ${r.status}`);const j=await r.json() as any;const out=(Array.isArray(j.data)?j.data:[]).map((x:any)=>({date:String(x.date||''),nav:Number(x.nav)})).filter((x:Point)=>x.date&&Number.isFinite(x.nav));return out.sort((a,b)=>{const [da,ma,ya]=a.date.split('-').map(Number),[db,mb,yb]=b.date.split('-').map(Number);return new Date(ya,ma-1,da).getTime()-new Date(yb,mb-1,db).getTime()});}
const median=(a:number[])=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
function maxDrawdown(series:number[]){let peak=-Infinity,dd=0;for(const x of series){peak=Math.max(peak,x);if(peak>0)dd=Math.min(dd,(x/peak-1)*100)}return dd;}
async function run(code:string,name:string,threshold:number,horizon:number){const d=await history(code),events:number[]=[],forward:number[]=[];for(let i=1;i<d.length-horizon;i++){const daily=(d[i].nav/d[i-1].nav-1)*100;if(daily<=-threshold){events.push(daily);forward.push((d[i+horizon].nav/d[i].nav-1)*100)}}const wins=forward.filter(x=>x>0).length;return{code,name,sampleCount:events.length,threshold,horizon,winRate:events.length?wins/events.length*100:null,averageForward:forward.length?forward.reduce((a,b)=>a+b,0)/forward.length:null,medianForward:median(forward),bestForward:forward.length?Math.max(...forward):null,worstForward:forward.length?Math.min(...forward):null,averageDip:events.length?events.reduce((a,b)=>a+b,0)/events.length:null,maxDrawdown:maxDrawdown(d.slice(-260).map(x=>x.nav))};}
export async function GET(req:Request){try{const u=new URL(req.url),threshold=Math.max(.25,Math.min(5,Number(u.searchParams.get('threshold')||1))),horizon=Math.max(5,Math.min(60,Number(u.searchParams.get('horizon')||20))),code=u.searchParams.get('code'),selected=code?funds.filter(x=>x[0]===code):funds;const results=(await Promise.all(selected.map(async([c,n])=>{try{return await run(c,n,threshold,horizon)}catch{return null}}))).filter((x):x is NonNullable<typeof x>=>x!==null).sort((a,b)=>(b.averageForward??-999)-(a.averageForward??-999));return NextResponse.json({threshold,horizon,results,generatedAt:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Backtest failed'},{status:500})}}
