import {NextResponse} from 'next/server';
export const dynamic='force-dynamic';export const revalidate=0;export const maxDuration=60;
type Point={date:string;nav:number};type Fund=[string,string];
const funds:Fund[]=[['120843','Quant Flexi Cap Fund Direct Growth'],['120826','Quant Large and Mid Cap Fund Direct Growth'],['120821','Quant Multi Asset Fund Direct Growth'],['120823','Quant Multi Cap Fund Direct Growth'],['120833','Quant Infrastructure Fund Direct Growth'],['151791','Quant BFSI Fund Direct Growth'],['119827','SBI Nifty 50 Index Fund Direct Growth'],['119783','SBI Healthcare Opportunities Fund Direct Growth'],['119727','SBI Focused Equity Fund Direct Growth'],['148490',"SBI Children's Benefit Fund Direct Growth"],['147946','Bandhan Small Cap Fund Direct Growth'],['118989','HDFC Mid Cap Opportunities Fund Direct Growth'],['143341','UTI Nifty Next 50 Index Fund Direct Growth'],['150714','UTI Gold ETF FoF Direct Growth'],['125497','SBI Small Cap Fund Direct Growth'],['120586','ICICI Prudential Value Discovery Fund Direct Growth'],['120503','Axis ELSS Tax Saver Fund Direct Growth'],['144835','Sundaram Services Fund Direct Growth'],['135800','Tata Digital India Fund Direct Growth']];
const headers={'User-Agent':'Mozilla/5.0 (compatible; AkashMutualFunds/6.0)','Accept':'application/json'};
async function history(code:string):Promise<Point[]>{try{const r=await fetch(`https://api.mfapi.in/mf/${code}`,{cache:'no-store',headers});if(!r.ok)throw new Error(`MFAPI ${r.status}`);const j=await r.json() as {data?:Array<{date?:string;nav?:string}>};return(Array.isArray(j.data)?j.data:[]).map((x):Point=>({date:String(x.date??''),nav:Number(x.nav)})).filter((x):boolean=>Boolean(x.date)&&Number.isFinite(x.nav)).sort((a:Point,b:Point)=>{const months:Record<string,number>={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};const [da,msa,ya]=a.date.split('-');const [db,msb,yb]=b.date.split('-');return new Date(Number(ya),months[msa]??0,Number(da)).getTime()-new Date(Number(yb),months[msb]??0,Number(db)).getTime();});}catch{return[];}}
function median(values:number[]):number|null{if(!values.length)return null;const sorted=[...values].sort((a:number,b:number)=>a-b),m=Math.floor(sorted.length/2);return sorted.length%2?sorted[m]:(sorted[m-1]+sorted[m])/2;}
function maxDrawdown(values:number[]):number{let peak=0,worst=0;for(const value of values){peak=Math.max(peak,value);if(peak>0)worst=Math.min(worst,(value/peak-1)*100);}return worst;}
async function run(code:string,name:string,threshold:number,horizon:number){const data=await history(code),forward:number[]=[],dips:number[]=[];for(let i=1;i<data.length-horizon;i++){const daily=(data[i].nav/data[i-1].nav-1)*100;if(daily<=-threshold){dips.push(daily);forward.push((data[i+horizon].nav/data[i].nav-1)*100);}}const wins=forward.filter((x:number)=>x>0).length;return{code,name,sampleCount:dips.length,threshold,horizon,winRate:dips.length?wins/dips.length*100:null,averageForward:forward.length?forward.reduce((a:number,b:number)=>a+b,0)/forward.length:null,medianForward:median(forward),bestForward:forward.length?Math.max(...forward):null,worstForward:forward.length?Math.min(...forward):null,averageDip:dips.length?dips.reduce((a:number,b:number)=>a+b,0)/dips.length:null,maxDrawdown:maxDrawdown(data.slice(-260).map((x:Point)=>x.nav))};}
export async function GET(req:Request){try{const url=new URL(req.url),threshold=Math.max(.25,Math.min(5,Number(url.searchParams.get('threshold')||1))),horizon=Math.max(5,Math.min(60,Number(url.searchParams.get('horizon')||20))),code=url.searchParams.get('code'),selected:Fund[]=code?funds.filter((x:Fund)=>x[0]===code):funds;const raw=await Promise.all(selected.map(async([c,n]:Fund)=>{try{return await run(c,n,threshold,horizon);}catch{return null;}}));const results=raw.filter((x):x is NonNullable<typeof x>=>x!==null).sort((a,b)=>(b.averageForward??-999)-(a.averageForward??-999));return NextResponse.json({threshold,horizon,results,generatedAt:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Backtest failed'},{status:500,headers:{'Cache-Control':'no-store'}});}}
